### ISSUE TITLE
Error: hrr_rb_ssh-0.4.1/lib/hrr_rb_ssh/connection.rb:241:in `channel_data': undefined method `receive_message_queue' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by hirura** [hirura/hrr_rb_ssh#23]
```
I, [2020-01-15T01:04:46.670327 #133617.3faa83b10748]  INFO -- HrrRbSsh::Connection[3faa54996284]: received SSH_MSG_CHANNEL_OPEN
D, [2020-01-15T01:04:46.670440 #133617.3faa83b10748] DEBUG -- HrrRbSsh::Message::SSH_MSG_CHANNEL_OPEN[3faa5fd8b62c]: decoded message: {:"message number"=>90, :"channel type"=>"session", :"sender channel"=>0, :"initial window size"=>2097152, :"maximum packet size"=>32768}
D, [2020-01-15T01:04:46.670619 #133617.3faa83b10748] DEBUG -- HrrRbSsh::Connection::Channel[3faa5fd8a63c]: in start:
I, [2020-01-15T01:04:46.670694 #133617.3faa5fd8a088]  INFO -- HrrRbSsh::Connection::Channel[3faa5fd8a63c]: start out sender thread
I, [2020-01-15T01:04:46.670764 #133617.3faa5fd8a178]  INFO -- HrrRbSsh::Connection::Channel[3faa5fd8a63c]: start channel loop thread
I, [2020-01-15T01:04:46.670867 #133617.3faa57f93e7c]  INFO -- HrrRbSsh::Connection::Channel[3faa5fd8a63c]: start err sender thread
I, [2020-01-15T01:04:46.670938 #133617.3faa57f93b34]  INFO -- HrrRbSsh::Connection::Channel::ChannelType::Session[3faa5fd8a4d4]: start proc chain thread
I, [2020-01-15T01:04:46.671000 #133617.3faa57f93d28]  INFO -- HrrRbSsh::Connection::Channel[3faa5fd8a63c]: start receiver thread
D, [2020-01-15T01:04:46.671087 #133617.3faa83b10748] DEBUG -- HrrRbSsh::Message::SSH_MSG_CHANNEL_OPEN_CONFIRMATION[3faa57f9338c]: encoding message: {:"message number"=>91, :"channel type"=>"session", :"recipient channel"=>0, :"sender channel"=>0, :"initial window size"=>100000, :"maximum packet size"=>100000}
I, [2020-01-15T01:04:46.782137 #133617.3faa83b10748]  INFO -- HrrRbSsh::Connection[3faa54996284]: received SSH_MSG_CHANNEL_REQUEST
D, [2020-01-15T01:04:46.782377 #133617.3faa83b10748] DEBUG -- HrrRbSsh::Message::SSH_MSG_CHANNEL_REQUEST[3faa57f949f8]: decoded message: {:"message number"=>98, :"recipient channel"=>0, :"request type"=>"subsystem", :"want reply"=>false, :"subsystem name"=>"netconf"}
I, [2020-01-15T01:04:46.782513 #133617.3faa5fd8a178]  INFO -- HrrRbSsh::Connection::Channel[3faa5fd8a63c]: received channel request: subsystem
D, [2020-01-15T01:04:46.783809 #133617.3faa5fd8a088] DEBUG -- HrrRbSsh::Message::SSH_MSG_CHANNEL_DATA[3faa5d8c1670]: encoding message: {:"message number"=>94, :"recipient channel"=>0, :data=>"<hello xmlns='urn:ietf:params:xml:ns:netconf:base:1.0'>\n  <capabilities>\n    <capability>urn:ietf:params:netconf:base:1.0</capability>\n    <capability>urn:ietf:params:netconf:base:1.1</capability>\n    <capability>urn:ietf:params:netconf:capability:writable-running:1.0</capability>\n    <capability>urn:ietf:params:netconf:capability:candidate:1.0</capability>\n    <capability>urn:ietf:params:netconf:capability:confirmed-commit:1.0</capability>\n    <capability>urn:ietf:params:netconf:capability:confirmed-commit:1.1</capability>\n    <capability>urn:ietf:params:netconf:capability:rollback-on-error:1.0</capability>\n    <capability>urn:ietf:params:netconf:capability:startup:1.0</capability>\n    <capability>urn:ietf:params:netconf:capability:validate:1.0</capability>\n    <capability>urn:ietf:params:netconf:capability:validate:1.1</capability>\n    <capability>urn:ietf:params:netconf:capability:url:1.0?scheme=http%2Cftp%2Cfile</capability>\n    <capability>urn:ietf:params:netconf:capability:xpath:1.0</capability>\n    <capability>urn:ietf:params:netconf:capability:notification:1.0</capability>\n  </capabilities>\n  <session-id>22</session-id>\n</hello>\n]]>]]>"}
I, [2020-01-15T01:04:46.799881 #133617.3faa83b10748]  INFO -- HrrRbSsh::Connection[3faa54996284]: received SSH_MSG_CHANNEL_CLOSE
D, [2020-01-15T01:04:46.800046 #133617.3faa83b10748] DEBUG -- HrrRbSsh::Message::SSH_MSG_CHANNEL_CLOSE[3faa5d8c0310]: decoded message: {:"message number"=>97, :"recipient channel"=>0}
I, [2020-01-15T01:04:46.800119 #133617.3faa83b10748]  INFO -- HrrRbSsh::Connection::Channel[3faa5fd8a63c]: close channel
D, [2020-01-15T01:04:46.800282 #133617.3faa83b10748] DEBUG -- HrrRbSsh::Message::SSH_MSG_CHANNEL_CLOSE[3faa5d8c3754]: encoding message: {:"message number"=>97, :"recipient channel"=>0}
I, [2020-01-15T01:04:46.800562 #133617.3faa5fd8a178]  INFO -- HrrRbSsh::Connection::Channel[3faa5fd8a63c]: closing channel loop thread
I, [2020-01-15T01:04:46.800653 #133617.3faa5fd8a178]  INFO -- HrrRbSsh::Connection::Channel[3faa5fd8a63c]: channel loop thread closed
I, [2020-01-15T01:04:46.800478 #133617.3faa83b10748]  INFO -- HrrRbSsh::Connection::Channel[3faa5fd8a63c]: channel closed
I, [2020-01-15T01:04:46.800785 #133617.3faa83b10748]  INFO -- HrrRbSsh::Connection[3faa54996284]: wait until threads closed in channel
I, [2020-01-15T01:04:46.800831 #133617.3faa57f93d28]  INFO -- HrrRbSsh::Connection::Channel[3faa5fd8a63c]: closing receiver thread
I, [2020-01-15T01:04:46.801086 #133617.3faa57f93d28]  INFO -- HrrRbSsh::Connection::Channel[3faa5fd8a63c]: closing w_io_in
I, [2020-01-15T01:04:46.801128 #133617.3faa57f93b34]  INFO -- HrrRbSsh::Connection::Channel::ChannelType::Session[3faa5fd8a4d4]: closing proc chain thread
I, [2020-01-15T01:04:46.801452 #133617.3faa57f93b34]  INFO -- HrrRbSsh::Connection::Channel::ChannelType::Session[3faa5fd8a4d4]: closing channel IOs
I, [2020-01-15T01:04:46.801363 #133617.3faa57f93d28]  INFO -- HrrRbSsh::Connection::Channel[3faa5fd8a63c]: w_io_in closed
I, [2020-01-15T01:04:46.801774 #133617.3faa57f93d28]  INFO -- HrrRbSsh::Connection::Channel[3faa5fd8a63c]: receiver thread closed
I, [2020-01-15T01:04:46.801832 #133617.3faa57f93e7c]  INFO -- HrrRbSsh::Connection::Channel[3faa5fd8a63c]: closing err sender thread
I, [2020-01-15T01:04:46.802013 #133617.3faa57f93e7c]  INFO -- HrrRbSsh::Connection::Channel[3faa5fd8a63c]: err sender thread closed
I, [2020-01-15T01:04:46.801897 #133617.3faa5fd8a088]  INFO -- HrrRbSsh::Connection::Channel[3faa5fd8a63c]: closing out sender thread
I, [2020-01-15T01:04:46.802078 #133617.3faa5fd8a088]  INFO -- HrrRbSsh::Connection::Channel[3faa5fd8a63c]: out sender thread closed
I, [2020-01-15T01:04:46.802215 #133617.3faa83b10748]  INFO -- HrrRbSsh::Connection[3faa54996284]: channel closed
I, [2020-01-15T01:04:46.802291 #133617.3faa83b10748]  INFO -- HrrRbSsh::Connection[3faa54996284]: deleting channel
I, [2020-01-15T01:04:46.801623 #133617.3faa57f93b34]  INFO -- HrrRbSsh::Connection::Channel::ChannelType::Session[3faa5fd8a4d4]: channel IOs closed
I, [2020-01-15T01:04:46.802416 #133617.3faa57f93b34]  INFO -- HrrRbSsh::Connection::Channel::ChannelType::Session[3faa5fd8a4d4]: wait for sending output
I, [2020-01-15T01:04:46.802461 #133617.3faa57f93b34]  INFO -- HrrRbSsh::Connection::Channel::ChannelType::Session[3faa5fd8a4d4]: sending output finished
I, [2020-01-15T01:04:46.802510 #133617.3faa57f93b34]  INFO -- HrrRbSsh::Connection::Channel::ChannelType::Session[3faa5fd8a4d4]: proc chain thread closed
I, [2020-01-15T01:04:46.802316 #133617.3faa83b10748]  INFO -- HrrRbSsh::Connection[3faa54996284]: channel deleted
I, [2020-01-15T01:04:48.320705 #133617.3faa83b10748]  INFO -- HrrRbSsh::Connection[3faa54996284]: received SSH_MSG_CHANNEL_DATA
D, [2020-01-15T01:04:48.320877 #133617.3faa83b10748] DEBUG -- HrrRbSsh::Message::SSH_MSG_CHANNEL_DATA[3faa5d3cee24]: decoded message: {:"message number"=>94, :"recipient channel"=>0, :data=>"<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n<hello xmlns=\"urn:ietf:params:xml:ns:netconf:base:1.0\">\n<capabilities>\n<capability>urn:ietf:params:netconf:capability:exi:1.0</capability>\n<capability>urn:ietf:params:netconf:base:1.1</capability>\n<capability>urn:ietf:params:netconf:base:1.0</capability>\n</capabilities>\n</hello>\n]]>]]>"}
E, [2020-01-15T01:04:48.322615 #133617.3faa83b10748] ERROR -- HrrRbSsh::Connection[3faa54996284]: /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/hrr_rb_ssh-0.4.1/lib/hrr_rb_ssh/connection.rb:241:in `channel_data': undefined method `receive_message_queue' for nil:NilClass (NoMethodError)
        /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/hrr_rb_ssh-0.4.1/lib/hrr_rb_ssh/connection.rb:116:in `block in connection_loop_thread'
I, [2020-01-15T01:04:48.322674 #133617.3faa83b10748]  INFO -- HrrRbSsh::Connection[3faa54996284]: closing connection loop
I, [2020-01-15T01:04:48.322699 #133617.3faa83b10748]  INFO -- HrrRbSsh::Connection[3faa54996284]: close connection
I, [2020-01-15T01:04:48.322722 #133617.3faa83b10748]  INFO -- HrrRbSsh::Authentication[3faa549962d4]: close authentication
I, [2020-01-15T01:04:48.322746 #133617.3faa83b10748]  INFO -- HrrRbSsh::Transport[3faa54996a7c]: close transport
I, [2020-01-15T01:04:48.322767 #133617.3faa83b10748]  INFO -- HrrRbSsh::Transport[3faa54996a7c]: disconnect transport
D, [2020-01-15T01:04:48.322821 #133617.3faa83b10748] DEBUG -- HrrRbSsh::Message::SSH_MSG_DISCONNECT[3faa5d3d1b24]: encoding message: {:"message number"=>1, :"reason code"=>11, :description=>"disconnected by user", :"language tag"=>""}
I, [2020-01-15T01:04:48.322936 #133617.3faa83b10748]  INFO -- HrrRbSsh::Transport[3faa54996a7c]: transport disconnected
I, [2020-01-15T01:04:48.322968 #133617.3faa83b10748]  INFO -- HrrRbSsh::Transport[3faa54996a7c]: transport closed
I, [2020-01-15T01:04:48.322988 #133617.3faa83b10748]  INFO -- HrrRbSsh::Authentication[3faa549962d4]: authentication closed
I, [2020-01-15T01:04:48.323015 #133617.3faa83b10748]  INFO -- HrrRbSsh::Connection::GlobalRequestHandler[3faa54996248]: closing tcpip-forward
I, [2020-01-15T01:04:48.323041 #133617.3faa83b10748]  INFO -- HrrRbSsh::Connection::GlobalRequestHandler[3faa54996248]: tcpip-forward closed
I, [2020-01-15T01:04:48.323061 #133617.3faa83b10748]  INFO -- HrrRbSsh::Connection[3faa54996284]: connection closed
I, [2020-01-15T01:04:48.323078 #133617.3faa83b10748]  INFO -- HrrRbSsh::Connection[3faa54996284]: connection loop closed
I, [2020-01-15T01:04:48.323160 #133617.3faa54997418]  INFO -- HrrRbSsh::Server[3faa8441ad48]: server service finished
```

**Comment by hirura** [comment]
When receiving channel related message after the channel is closed, then it raises the error.
