### ISSUE TITLE
Error: hrr_rb_ssh-0.4.1/lib/hrr_rb_ssh/transport/sender.rb:41:in `write': closed stream (IOError)

### ISSUE THREAD

**Issue by hirura** [hirura/hrr_rb_ssh#24]
```
I, [2020-01-15T01:06:30.868988 #133567.3faa73bab7a8]  INFO -- HrrRbSsh::Connection[3faa5f7c14bc]: closing connection loop
I, [2020-01-15T01:06:30.869045 #133567.3faa73bab7a8]  INFO -- HrrRbSsh::Connection[3faa5f7c14bc]: close connection
I, [2020-01-15T01:06:30.869077 #133567.3faa73bab7a8]  INFO -- HrrRbSsh::Authentication[3faa5f7c1520]: close authentication
I, [2020-01-15T01:06:30.869114 #133567.3faa73bab7a8]  INFO -- HrrRbSsh::Transport[3faa59bb42f0]: close transport
I, [2020-01-15T01:06:30.869142 #133567.3faa73bab7a8]  INFO -- HrrRbSsh::Transport[3faa59bb42f0]: disconnect transport
D, [2020-01-15T01:06:30.869270 #133567.3faa73bab7a8] DEBUG -- HrrRbSsh::Message::SSH_MSG_DISCONNECT[3faa73bab76c]: encoding message: {:"message number"=>1, :"reason code"=>11, :description=>"disconnected by user", :"language tag"=>""}
E, [2020-01-15T01:06:30.869489 #133567.3faa73bab7a8] ERROR -- HrrRbSsh::Transport[3faa59bb42f0]: /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/hrr_rb_ssh-0.4.1/lib/hrr_rb_ssh/transport/sender.rb:41:in `write': closed stream (IOError)
        /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/hrr_rb_ssh-0.4.1/lib/hrr_rb_ssh/transport/sender.rb:41:in `send_packet'
        /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/hrr_rb_ssh-0.4.1/lib/hrr_rb_ssh/transport/sender.rb:52:in `send'
        /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/hrr_rb_ssh-0.4.1/lib/hrr_rb_ssh/transport.rb:93:in `block in send'
        /root/.rbenv/versions/2.6.5/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
        /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/hrr_rb_ssh-0.4.1/lib/hrr_rb_ssh/transport.rb:91:in `send'
        /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/hrr_rb_ssh-0.4.1/lib/hrr_rb_ssh/transport.rb:359:in `send_disconnect'
        /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/hrr_rb_ssh-0.4.1/lib/hrr_rb_ssh/transport.rb:211:in `disconnect'
        /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/hrr_rb_ssh-0.4.1/lib/hrr_rb_ssh/transport.rb:196:in `close'
        /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/hrr_rb_ssh-0.4.1/lib/hrr_rb_ssh/authentication.rb:66:in `close'
        /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/hrr_rb_ssh-0.4.1/lib/hrr_rb_ssh/connection.rb:73:in `close'
        /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/hrr_rb_ssh-0.4.1/lib/hrr_rb_ssh/connection.rb:131:in `ensure in block in connection_loop_thread'
        /root/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/hrr_rb_ssh-0.4.1/lib/hrr_rb_ssh/connection.rb:132:in `block in connection_loop_thread'
W, [2020-01-15T01:06:30.869552 #133567.3faa73bab7a8]  WARN -- HrrRbSsh::Transport[3faa59bb42f0]: Transport is closed
I, [2020-01-15T01:06:30.869584 #133567.3faa73bab7a8]  INFO -- HrrRbSsh::Transport[3faa59bb42f0]: transport disconnected
I, [2020-01-15T01:06:30.869614 #133567.3faa73bab7a8]  INFO -- HrrRbSsh::Transport[3faa59bb42f0]: transport closed
I, [2020-01-15T01:06:30.869642 #133567.3faa73bab7a8]  INFO -- HrrRbSsh::Authentication[3faa5f7c1520]: authentication closed
I, [2020-01-15T01:06:30.869678 #133567.3faa73bab7a8]  INFO -- HrrRbSsh::Connection::Channel[3faa6a9f2578]: close channel
D, [2020-01-15T01:06:30.869738 #133567.3faa73bab7a8] DEBUG -- HrrRbSsh::Message::SSH_MSG_CHANNEL_CLOSE[3faa73baf484]: encoding message: {:"message number"=>97, :"recipient channel"=>0}
I, [2020-01-15T01:06:32.076845 #133567.3faa73bab7a8]  INFO -- HrrRbSsh::Connection::Channel[3faa6a9f2578]: channel closed
I, [2020-01-15T01:06:32.076943 #133567.3faa73bab7a8]  INFO -- HrrRbSsh::Connection::GlobalRequestHandler[3faa5f7c1458]: closing tcpip-forward
I, [2020-01-15T01:06:32.076976 #133567.3faa73bab7a8]  INFO -- HrrRbSsh::Connection::GlobalRequestHandler[3faa5f7c1458]: tcpip-forward closed
I, [2020-01-15T01:06:32.077007 #133567.3faa73bab7a8]  INFO -- HrrRbSsh::Connection[3faa5f7c14bc]: connection closed
I, [2020-01-15T01:06:32.077037 #133567.3faa73bab7a8]  INFO -- HrrRbSsh::Connection[3faa5f7c14bc]: connection loop closed
```

**Comment by hirura** [comment]
When sending some message onto closed IO, then this kind of error is shown.
