### ISSUE TITLE
`start': wrong number of arguments (given 1, expected 0)

### ISSUE THREAD

**Issue by bolandross** [hirura/hrr_rb_ssh#3]
Hey, I'm having some trouble running the "writing standard ssh server" example. 

I start the simple server script, and everytime I try to connect to it, I am getting this on the server side:

    var/lib/gems/2.3.0/gems/hrr_rb_ssh-0.2.2/lib/hrr_rb_ssh/server.rb:18:in `start':
    wrong number of arguments (given 1, expected 0) (ArgumentError)

running ruby 2.3.3p222, any ideas what I'm missing?

Thank you very much in advance

**Comment by KINGSABRI** [comment]
Same issue here
I commented out the extract argument on line 104 and another error occurred. 
```
I, [2019-05-26T20:41:57.016848 #18891]  INFO -- : process 18895 started
I, [2019-05-26T20:41:57.018092 #18895]  INFO -- : HrrRbSsh::Server: start server service
I, [2019-05-26T20:41:57.018267 #18895]  INFO -- : HrrRbSsh::Transport: start transport
E, [2019-05-26T20:41:57.020174 #18895] ERROR -- : HrrRbSsh::Transport: /var/lib/gems/2.5.0/gems/hrr_rb_ssh-0.2.2/lib/hrr_rb_ssh/transport.rb:307:in `send_version': undefined method `write' for #<Hash:0x00005649ee917d30> (NoMethodError)
        /var/lib/gems/2.5.0/gems/hrr_rb_ssh-0.2.2/lib/hrr_rb_ssh/transport.rb:212:in `exchange_version'
        /var/lib/gems/2.5.0/gems/hrr_rb_ssh-0.2.2/lib/hrr_rb_ssh/transport.rb:164:in `start'
        /var/lib/gems/2.5.0/gems/hrr_rb_ssh-0.2.2/lib/hrr_rb_ssh/authentication.rb:46:in `start'
        /var/lib/gems/2.5.0/gems/hrr_rb_ssh-0.2.2/lib/hrr_rb_ssh/connection.rb:47:in `start'
        /var/lib/gems/2.5.0/gems/hrr_rb_ssh-0.2.2/lib/hrr_rb_ssh/server.rb:20:in `start'
        ssh-server.rb:104:in `start_service'
        ssh-server.rb:117:in `block (3 levels) in <main>'
        ssh-server.rb:115:in `fork'
        ssh-server.rb:115:in `block (2 levels) in <main>'
I, [2019-05-26T20:41:57.020304 #18895]  INFO -- : HrrRbSsh::Transport: close transport
I, [2019-05-26T20:41:57.020333 #18895]  INFO -- : HrrRbSsh::Transport: disconnect transport
E, [2019-05-26T20:41:57.021944 #18895] ERROR -- : HrrRbSsh::Transport: /var/lib/gems/2.5.0/gems/hrr_rb_ssh-0.2.2/lib/hrr_rb_ssh/transport/sender.rb:39:in `send_packet': undefined method `write' for #<Hash:0x00005649ee917d30> (NoMethodError)
        /var/lib/gems/2.5.0/gems/hrr_rb_ssh-0.2.2/lib/hrr_rb_ssh/transport/sender.rb:50:in `send'
        /var/lib/gems/2.5.0/gems/hrr_rb_ssh-0.2.2/lib/hrr_rb_ssh/transport.rb:91:in `block in send'
        /usr/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
        /var/lib/gems/2.5.0/gems/hrr_rb_ssh-0.2.2/lib/hrr_rb_ssh/transport.rb:89:in `send'
        /var/lib/gems/2.5.0/gems/hrr_rb_ssh-0.2.2/lib/hrr_rb_ssh/transport.rb:347:in `send_disconnect'
        /var/lib/gems/2.5.0/gems/hrr_rb_ssh-0.2.2/lib/hrr_rb_ssh/transport.rb:202:in `disconnect'
        /var/lib/gems/2.5.0/gems/hrr_rb_ssh-0.2.2/lib/hrr_rb_ssh/transport.rb:187:in `close'
        /var/lib/gems/2.5.0/gems/hrr_rb_ssh-0.2.2/lib/hrr_rb_ssh/transport.rb:177:in `rescue in start'
        /var/lib/gems/2.5.0/gems/hrr_rb_ssh-0.2.2/lib/hrr_rb_ssh/transport.rb:163:in `start'
        /var/lib/gems/2.5.0/gems/hrr_rb_ssh-0.2.2/lib/hrr_rb_ssh/authentication.rb:46:in `start'
        /var/lib/gems/2.5.0/gems/hrr_rb_ssh-0.2.2/lib/hrr_rb_ssh/connection.rb:47:in `start'
        /var/lib/gems/2.5.0/gems/hrr_rb_ssh-0.2.2/lib/hrr_rb_ssh/server.rb:20:in `start'
        ssh-server.rb:104:in `start_service'
        ssh-server.rb:117:in `block (3 levels) in <main>'
        ssh-server.rb:115:in `fork'
        ssh-server.rb:115:in `block (2 levels) in <main>'
E, [2019-05-26T20:41:57.022069 #18895] ERROR -- : HrrRbSsh::Transport: /var/lib/gems/2.5.0/gems/hrr_rb_ssh-0.2.2/lib/hrr_rb_ssh/transport.rb:99:in `rescue in block in send': HrrRbSsh::Error::ClosedTransport (HrrRbSsh::Error::ClosedTransport)
        /var/lib/gems/2.5.0/gems/hrr_rb_ssh-0.2.2/lib/hrr_rb_ssh/transport.rb:90:in `block in send'
        /usr/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
        /var/lib/gems/2.5.0/gems/hrr_rb_ssh-0.2.2/lib/hrr_rb_ssh/transport.rb:89:in `send'
        /var/lib/gems/2.5.0/gems/hrr_rb_ssh-0.2.2/lib/hrr_rb_ssh/transport.rb:347:in `send_disconnect'
        /var/lib/gems/2.5.0/gems/hrr_rb_ssh-0.2.2/lib/hrr_rb_ssh/transport.rb:202:in `disconnect'
        /var/lib/gems/2.5.0/gems/hrr_rb_ssh-0.2.2/lib/hrr_rb_ssh/transport.rb:187:in `close'
        /var/lib/gems/2.5.0/gems/hrr_rb_ssh-0.2.2/lib/hrr_rb_ssh/transport.rb:177:in `rescue in start'
        /var/lib/gems/2.5.0/gems/hrr_rb_ssh-0.2.2/lib/hrr_rb_ssh/transport.rb:163:in `start'
        /var/lib/gems/2.5.0/gems/hrr_rb_ssh-0.2.2/lib/hrr_rb_ssh/authentication.rb:46:in `start'
        /var/lib/gems/2.5.0/gems/hrr_rb_ssh-0.2.2/lib/hrr_rb_ssh/connection.rb:47:in `start'
        /var/lib/gems/2.5.0/gems/hrr_rb_ssh-0.2.2/lib/hrr_rb_ssh/server.rb:20:in `start'
        ssh-server.rb:104:in `start_service'
        ssh-server.rb:117:in `block (3 levels) in <main>'
        ssh-server.rb:115:in `fork'
        ssh-server.rb:115:in `block (2 levels) in <main>'
I, [2019-05-26T20:41:57.022104 #18895]  INFO -- : HrrRbSsh::Transport: transport disconnected
I, [2019-05-26T20:41:57.022127 #18895]  INFO -- : HrrRbSsh::Transport: transport closed
E, [2019-05-26T20:41:57.022197 #18895] ERROR -- : /var/lib/gems/2.5.0/gems/hrr_rb_ssh-0.2.2/lib/hrr_rb_ssh/transport.rb:105:in `receive': HrrRbSsh::Error::ClosedTransport (HrrRbSsh::Error::ClosedTransport)
        /var/lib/gems/2.5.0/gems/hrr_rb_ssh-0.2.2/lib/hrr_rb_ssh/authentication.rb:67:in `block in authenticate'
        /var/lib/gems/2.5.0/gems/hrr_rb_ssh-0.2.2/lib/hrr_rb_ssh/authentication.rb:66:in `loop'
        /var/lib/gems/2.5.0/gems/hrr_rb_ssh-0.2.2/lib/hrr_rb_ssh/authentication.rb:66:in `authenticate'
        /var/lib/gems/2.5.0/gems/hrr_rb_ssh-0.2.2/lib/hrr_rb_ssh/authentication.rb:47:in `start'
        /var/lib/gems/2.5.0/gems/hrr_rb_ssh-0.2.2/lib/hrr_rb_ssh/connection.rb:47:in `start'
        /var/lib/gems/2.5.0/gems/hrr_rb_ssh-0.2.2/lib/hrr_rb_ssh/server.rb:20:in `start'
        ssh-server.rb:104:in `start_service'
        ssh-server.rb:117:in `block (3 levels) in <main>'
        ssh-server.rb:115:in `fork'
        ssh-server.rb:115:in `block (2 levels) in <main>'
I, [2019-05-26T20:41:57.026930 #18891]  INFO -- : process 18895 finished with status #<Process::Status: pid 18895 exit 1>

```

**Comment by sempervictus** [comment]
Small world, kingsabri is here already. I can only imagine the nefarious reasons for why. ;-)

I'll be diving into this a bit during the metasploit hackathon this weekend to try and build those rev-ssh handlers we've needed forever. Chances are I'll run into this one pretty quick if its such an easy repro. Will try to find and fix/PR as I go.

**Comment by hirura** [comment]
Hi all,
I have updated the Server#initialize and Server#start code so that the server can be instantiated with no IO instance, and pass some IO instance at start.
Now the README and demos in master branch is newer style than the gem version 0.2.2.
Please follow instructions and demos under version 0.2.2 tag (https://github.com/hirura/hrr_rb_ssh/tree/v0.2.2).
Thanks,

**Comment by hirura** [comment]
Hi all,

Still having trouble ?
I have released [v0.3.0.pre2](https://rubygems.org/gems/hrr_rb_ssh/versions/0.3.0.pre2). Please try it as well.

```sh
gem install hrr_rb_ssh --pre
```

**Comment by bolandross** [comment]
Hey and thank you.

The demo files run fine using the suggested version of the gem!

**Comment by hirura** [comment]
That's good! Thanks for the confirmation.
